apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: 9862672975/tickets
          env:
            - name : NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL 
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: CLOUDINARY_API_KEY
              value: "416529793865753"
            - name: CLOUDINARY_SECRET 
              value: "vkWeACucGKBhI64IODHVqQgepNI"
            - name: CLOUDINARY_URL
              value: "cloudinary://416529793865753:vkWeACucGKBhI64IODHVqQgepNI@ayushniroula" 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4000
      targetPort: 4000
